### ISSUE TITLE
Roadmap for Pykoala object containers

### ISSUE THREAD

**Issue by YourLocalBlake** [pykoala/koala#146]
- [ ] Upload containers directory: containing containers.py - has base objects, initialisers.py - has functions for initialising the base objects
- [ ] Update doc strings for containers.py
- [ ] Upload loaders.py - - has the functions for reading in the .yml config files 
- [ ]  Add tests for the above-mentioned with example .yml files
- [ ] Implement above-mentioned into main code to replace hard-coded strings for file locations
- [ ] Implement CubeObject and resulting loaders, tests, etc...
------------------
- [ ] _throughout_ continue to build base RSSobject class and refine as __init__.py and __main__.py are refactored
- [ ] _throughout_ update _utils.py for the RSSobject as the above refactoring takes place
------------------
Only mark completed when merged.
